export const ADD_TREASURE = "ADD_TREASURE";
export const ADD_TREASURE_ERROR = "ADD_TREASURE_ERROR";

export const DELETE_TREASURE = "DELETE_TREASURE";
export const DELETE_TREASURE_ERROR = "DELETE_TREASURE_ERROR";

export const EDIT_TREASURE = "EDIT_TREASURE";
export const EDIT_TREASURE_ERROR = "EDIT_TREASURE_ERROR";
